version: '3.9'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: starshop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/starshop?sslmode=disable
      - JWT_SECRET=your-secret-key
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
