name: CI - Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install

    - name: Set Environment Variables
      run: echo "NODE_ENV=test" >> $GITHUB_ENV

    - name: Run Tests
      run: npm test

    - name: Debug on Failure
      if: failure()
      run: |
        echo "Tests failed. Debugging logs:"
        cat test-results.log || echo "No logs found"
